spring:
  application:
    name: worker-consumer-feign
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true


# 配置ribbon的超时时间
ribbon:
  ReadTimeout: 3000   #读超时
  ConnectTimeout: 3000  #连接超时
# 配置hystrix的超时时间为3秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
