dubbo:
  application:
    name: view-facade
  registry:
    address: zookeeper://192.168.85.132:2181
  protocol:
    port: 20881
server:
  port: 9091



# 指明mapper映射文件的位置
mybatis:
  mapper-locations: classpath:META-INF/mapper/*.xml

# 配置连接池Druid
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test01?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
